export const COLOR_PRIMARY = "#6eb833"

// 控件尺寸
export const SIZE_CONTROL_NORMAL = 30
export const SIZE_CONTROL_PADDING_INLINE_NORMAL = 10
export const SIZE_CONTROL_PADDING_BLOCK_NORMAL = 5
export const SIZE_CONTROL_MARGIN_INLINE_NORMAL = 5
export const SIZE_CONTROL_MARGIN_BLOCK_NORMAL = 5
export const SIZE_CONTROL_LABEL_NORMAL = 18
export const SIZE_CONTROL_BORDER_RADUS = 3